@appJson = application/json


POST {{baseAddress}}/servicebus
Accept: {{appJson}}
Content-Type: {{appJson}}

{
    "text": "I am a new message",
    "tags": [
      "tag1",
      "tag2"
    ]
}

### Publish a new message


GET {{baseAddress}}/servicebus/receive

### View a message


GET {{baseAddress}}/servicebus/receive-messages?max=5

### View messages


GET {{baseAddress}}/servicebus/peek?start=0

### View a message


GET {{baseAddress}}/servicebus/peek-messages?max=5&start=0

### View messages